
on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.9
